name: Build OrangeFox Recovery

on:
  push:        
    branches:  [ ofox ]
  pull_request: 
    branches:  [ ofox ]



jobs:
  build:
    name: Build OFRP by ${{ github.actor }}
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Clean-up
      uses: rokibhasansagar/slimhub_actions@main

    - name: Swap Space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 12

    - name: Setup ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        max-size: "10G"

    - name: Build OrangeFox Recovery
      uses: mlm-games/OrangeFox-Builder-Action@main 
      id: build
      with:
        MANIFEST_BRANCH: '12.1'
        DEVICE_TREE: 'https://github.com/mlm-games/ofox_m31s'
        DEVICE_TREE_BRANCH: 'android-12.1'
        DEVICE_NAME: 'm31s'
        DEVICE_PATH: 'device/samsung/m31s'
        BUILD_TARGET: 'recovery'

    - name: Upload to Release        # Github artifact action eats your space even if you delete the artifacts :\
      uses: softprops/action-gh-release@v1
      if: success()
      with:
        files: |
          ${{ env.OUTPUT_DIR }}/OrangeFox*.img
          ${{ env.OUTPUT_DIR }}/OrangeFox*.tar
          ${{ env.OUTPUT_DIR }}/OrangeFox*.zip
          ${{ env.OUTPUT_DIR }}/ramdisk-recovery.*
        name: Unofficial OrangeFox for ${{ env.DEVICE_NAME }} // ${{ env.BUILD_DATE }}
        tag_name: ${{ github.run_id }}
        body: |
          Build: ${{ env.MANIFEST_BRANCH }}
          Device: [Device Tree/Branch](${{ env.DEVICE_TREE }}/tree/${{ env.DEVICE_TREE_BRANCH }})
          Commit: Most recent [commit](${{ env.DEVICE_TREE }}/commit/${{ env.COMMIT_ID }}) during building.
          MD5 (img): ${{ env.MD5_IMG }}
          MD5 (zip): ${{ env.MD5_ZIP }}
        prerelease: true